medical_profile:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: MyRealPassword123  # <-- Inserted your real password here
      port: 5432
      dbname: medical_warehouse
      schema: main
      threads: 4
  target: dev